### ISSUE TITLE
Upgrade to JUnit Jupiter 5.0.0-RC2

### ISSUE THREAD

**Issue by bamapookie** [sbrannen/spring-test-junit5#13]
Would it be possible to update JitPack to cover the RC builds? Junit5 is up to 5.0.0-RC2

Thanks.

**Comment by sbrannen** [comment]
There's no specific need to upgrade to JUnit Jupiter 5.0 RC2 since the code in the `1.0.0.M6` tag should work just fine with JUnit Jupiter 5.0 RC2.

Nonetheless, I've upgraded the build to 5.0 RC2, updated the README, and tagged the repository accordingly. 

I would have done it sooner, but I was on vacation. 😉

**Comment by sbrannen** [comment]
See https://github.com/sbrannen/spring-test-junit5/releases/tag/1.0.0.RC2
